# Ndarray

In [1]:
import numpy as np

In [2]:
an_array = np.array([3, 33, 333])

In [3]:
print(type(an_array))

<class 'numpy.ndarray'>


In [5]:
# 1d array with 3 elements
print(an_array.shape)

(3,)


In [7]:
# 2d array (matrix)
matrix = np.array([[1,2,3], [4,5,6]])

In [8]:
matrix.shape

(2, 3)

# Indexing

In [9]:
matrix2 = np.array([[11, 12, 13, 14],
                   [21, 22, 23, 24],
                   [31,32,33,34]])
print(matrix2)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [10]:
# [row_slice, column_slice]
matrix2[:2, 1:3]

array([[12, 13],
       [22, 23]])

In [11]:
# slicing gives a reference to the subset of the original matrix
# use array constructor to get the copy
a_slice = np.array(matrix[:2, 1:3])
a_slice[0][0] = 125
print(a_slice, matrix2[:2, 1:3])

[[125   3]
 [  5   6]] [[12 13]
 [22 23]]


In [14]:
# : means slice all columns
row_slice = matrix2[1, :]
print(row_slice, row_slice.shape)

[21 22 23 24] (4,)


In [15]:
# fast way of selecting array values
# create an array of indices
col_indices = np.array([0,1,2,0])
row_indices = np.arange(4)

In [16]:
print(col_indices)
print(row_indices)

[0 1 2 0]
[0 1 2 3]


In [18]:
matrix3 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])

In [19]:
matrix3[row_indices, col_indices]

array([ 1,  5,  9, 10])

# Boolean indexing

In [20]:
filter = (matrix3 > 7)

In [22]:
filter

array([[False, False, False],
       [False, False, False],
       [False,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [21]:
matrix3[matrix3 > 7]

array([ 8,  9, 10, 11, 12])

In [26]:
# use bitwise and i.e & instead of and 
matrix3[(matrix3 > 5) & (matrix3 % 2 == 0)]

array([ 6,  8, 10, 12])

# Datatypes and  operations

In [27]:
# allocate an array of type "object"
# useful for having an array of custom objects
my_type = np.array((3), dtype = object)

In [28]:
my_type

array(3, dtype=object)

In [29]:
# arithmetic operations
x = np.array([[1,2,3],[3,2,3],[2,4,5]], dtype = np.int64)

In [30]:
np.sqrt(x)

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 1.73205081,  1.41421356,  1.73205081],
       [ 1.41421356,  2.        ,  2.23606798]])

In [31]:
arr = 10 * np.random.randn(2,5)

In [32]:
print(arr.mean())

-3.02202910028


In [33]:
# compute by row
print(arr.mean(axis = 1))

[-3.51046968 -2.53358852]


In [34]:
# compute by column
print(arr.mean(axis = 0))

[ 2.79512006 -7.98995041 -3.80047591 -4.2471434  -1.86769584]


In [35]:
# sum all elements
arr.sum()

-30.220291002753193

In [36]:
print(np.median(arr, axis = 1))

[-0.76945635 -3.14255812]


In [37]:
np.unique(x)

array([1, 2, 3, 4, 5])

# Broadcasting

In [38]:
# add matrix to vector :
# eg. add a vector to each row of a matrix
start = np.zeros((4,3))
row = np.array([1,0,2])

In [39]:
y = start + row

In [40]:
print(y)

[[ 1.  0.  2.]
 [ 1.  0.  2.]
 [ 1.  0.  2.]
 [ 1.  0.  2.]]


In [41]:
col = np.array([[0,1,2,3]])
col = col.T

In [42]:
y = start + col

In [44]:
print(y)

[[ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]]


In [45]:
start + 1

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])